import "@zapcron/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { ConfigProvider, HeroUIProvider } from "@zapcron/providers";
import { TRPCReactProvider } from "@zapcron/trpc/react";

export const metadata: Metadata = {
  title: "ZapCron",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const config = {
    debug: process.env.DEBUG === "true",
  };
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <HeroUIProvider
            themeProps={{
              attribute: "class",
              defaultTheme: "dark",
            }}
          >
            <ConfigProvider config={config}>{children}</ConfigProvider>
          </HeroUIProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
