import "@zapcron/styles/globals.css";

import { ConfigProvider, HeroUIProvider } from "@zapcron/providers";
import { TRPCReactProvider } from "@zapcron/trpc/react";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { cloakSSROnlySecret } from "ssr-only-secrets";

export const metadata: Metadata = {
  title: "ZapCron",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const config = {
    debug: process.env.DEBUG === "true",
  };
  const cookie = (await headers()).get("cookie");
  const encryptedCookie = await cloakSSROnlySecret(
    cookie ?? "",
    "SECRET_CLIENT_COOKIE_VAR",
  );
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider ssrOnlySecret={encryptedCookie}>
          <HeroUIProvider
            themeProps={{
              attribute: "class",
              defaultTheme: "dark",
            }}
          >
            <ConfigProvider config={config}>{children}</ConfigProvider>
          </HeroUIProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
