import { type Metadata } from "next";

import { Sidebar } from "@bolabali/app/_components/layout";

export const metadata: Metadata = {
  title: "Bolabali | Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex min-h-screen">
      <aside className="w-80">
        <Sidebar />
      </aside>
      <aside className="flex-auto">{children}</aside>
    </div>
  );
}
