import { type Metadata } from "next";
import { redirect } from "next/navigation";
import { SessionProvider } from "next-auth/react";

import { auth } from "@zapcron/server/auth";
import { Header, Sidebar } from "@zapcron/components/layout";

export const metadata: Metadata = {
  title: "ZapCron | Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  if (!session?.user) return redirect("/");
  return (
    <div className="relative">
      <SessionProvider session={session}>
        <Header user={session.user} />
        <div className="flex min-h-screen">
          <Sidebar user={session.user} />
          <aside className="flex-auto">{children}</aside>
        </div>
      </SessionProvider>
    </div>
  );
}
